### ISSUE TITLE
How do I get the new version to work?

### ISSUE THREAD

**Issue by usernameowner69** [AzureDoom/MCDoom#114]
I don't understand the build.gradle thing in the description.

**Comment by AzureDoom** [comment]
You don't use anything regarding build.gradle, you simply install the mod, and it's required mods, which are marked per file on both CurseForge and Modrinth.

**Comment by usernameowner69** [comment]
[crash-2023-09-21_22.43.35-fml.txt](https://github.com/AzureDoom/MCDoom/files/12693554/crash-2023-09-21_22.43.35-fml.txt)


It still crashed, did I download the wrong version of anything? Running on neoforge, latest version of geckolib, azurelib, curios and smartbrain.

**Comment by AzureDoom** [comment]
Read the patch notes please

**Comment by usernameowner69** [comment]
Not sure which part you're referring to, I did download the new portals API.

**Comment by AzureDoom** [comment]
```
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/kyrptonaught/customportalapi/api/CustomPortalBuilder
```
You in fact did not.

**Comment by usernameowner69** [comment]
I put cpapireforged-1.0.0.jar in my mods folder, I can't really think of anything else I can do.

**Comment by usernameowner69** [comment]
The newest portals api version worked, thanks.

**Comment by WilliamBlaze** [comment]
i found out the cause of all the crashes from the last forge 1.20.1 version - and the same source is continuing to crash the Neo forge version's release. a simple mod called "
Cloth Config API (Fabric/Forge)" the Forge version specifically. And sadly its a mandatory file requirement for anyone wanting to use the "Better combat" mod both on forge or its fabric version. Essentially this means you can no longer run MCDoom and better combat(forge version) at the same time on forge, and players are currently forced to make a choice of one or the other.

Or... the temporary work around i found that works without causing the NeoForge version of MCDoom to crash - Just run the fabric version of better combat instead of the forge version!

The steps for that requires having "Forgified Fabric API" & "Sinytra Connector" in the mod folder along with Fabric versions of the following mods: Cloth Config API, PlayerAnimator, and Better Combat.

Highly unorthodox as it is, it's a working work around that functions well enough to get the job done without crashing anything, even if not all forge mod weapons will register the correct animations (which lets face it is a problem that all versions of Better combat have, but at least there's a way to manually fix that in the config files if you take the time to do so.)


I figured now that I discovered the cause of all the strange crashes I was getting, it was worth sharing here since Better Combat is still listed as an optional dependency for MCDoom.

Also yeah, I also discovered usernameowner69's bug when i tried having the Atlantis mod installed at the same time as MCDoom. that crash is caused because both mods use different versions of the Custom Portal API, causing conflict. Kinda wish there was a universal fix to that, but meh, i can live without the all ocean filled dimension, MCDoom is something i've been trying to get working with my ideal mod pack literally since 2021, now that i got a solution to the biggest wall i've faced thus far, i can finally go into full on testing!

**Comment by AzureDoom** [comment]
> i found out the cause of all the crashes from the last forge 1.20.1 version - and the same source is continuing to crash the Neo forge version's release. a simple mod called " Cloth Config API (Fabric/Forge)" the Forge version specifically. And sadly its a mandatory file requirement for anyone wanting to use the "Better combat" mod both on forge or its fabric version. Essentially this means you can no longer run MCDoom and better combat(forge version) at the same time on forge, and players are currently forced to make a choice of one or the other.
> 
> Or... the temporary work around i found that works without causing the NeoForge version of MCDoom to crash - Just run the fabric version of better combat instead of the forge version!
> 
> The steps for that requires having "Forgified Fabric API" & "Sinytra Connector" in the mod folder along with Fabric versions of the following mods: Cloth Config API, PlayerAnimator, and Better Combat.
> 
> Highly unorthodox as it is, it's a working work around that functions well enough to get the job done without crashing anything, even if not all forge mod weapons will register the correct animations (which lets face it is a problem that all versions of Better combat have, but at least there's a way to manually fix that in the config files if you take the time to do so.)
> 
> I figured now that I discovered the cause of all the strange crashes I was getting, it was worth sharing here since Better Combat is still listed as an optional dependency for MCDoom.
> 
> Also yeah, I also discovered usernameowner69's bug when i tried having the Atlantis mod installed at the same time as MCDoom. that crash is caused because both mods use different versions of the Custom Portal API, causing conflict. Kinda wish there was a universal fix to that, but meh, i can live without the all ocean filled dimension, MCDoom is something i've been trying to get working with my ideal mod pack literally since 2021, now that i got a solution to the biggest wall i've faced thus far, i can finally go into full on testing!

![Screenshot 2023-09-28 155015](https://github.com/AzureDoom/MCDoom/assets/7415711/52707dea-fa4e-4922-93d5-7464a88e09c4)
Colth was actually fixed and so was custom portals.
