### ISSUE TITLE
Mod has failed to load correctly

### ISSUE THREAD

**Issue by RNonsense** [AzureDoom/MCDoom#60]
When I run the latest forge version or the mod it says the Doom mod failed to load correctly.
[crash-2022-08-02_17.19.03-fml.txt](https://github.com/AzureDoom/MCDoom/files/9242367/crash-2022-08-02_17.19.03-fml.txt)

**Comment by AzureDoom** [comment]
You are missing Curios, please properly read the required mods.

**Comment by emilyallerdings** [comment]
No where in your dependencies or main page on curseforge does it say that Curios is required. Had to look through these closed issues just to figure out what dependencies your mod requires, just to see you smugly saying to "read the required mods".

**Comment by AzureDoom** [comment]
> No where in your dependencies or main page on curseforge does it say that Curios is required. Had to look through these closed issues just to figure out what dependencies your mod requires, just to see you smugly saying to "read the required mods".

![image](https://user-images.githubusercontent.com/7415711/185443880-1592e40c-29f6-41ee-8d77-e0be447c1f29.png)
You are just one blind motherfucker then.

**Comment by emilyallerdings** [comment]
![lol](https://user-images.githubusercontent.com/17506903/185721052-a10ce7a2-c04f-4943-b0f3-76ac0f533d84.PNG)
There's a different dependency page that is right out in the open that doesn't state any of this, you know the one that people are most likely to check.

**Comment by emilyallerdings** [comment]
Ok fine. Honestly I didn't know about the other dependency page and only used the relations dependency page before. I assume this only shows one version's dependencies (the Fabric version) so that is why I was confused. I assume that other people will also continue to make this mistake because they don't know the per-version dependency pages exist, though I feel like this is more of Curseforge's fault than yours. 
So sorry for being an ass to you, but can you please just not be smug about it and instead tell people where to go to see the dependencies?

**Comment by AzureDoom** [comment]
That is a failure of CurseForge, not the mod page. Go bark up their asses. My files are tagged with dependencies correctly as I have shown.
