### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wsxiya** [AzureDoom/MCDoom#81]
The attack power of Marauder Argent Ax in version 1.19.2forge is displayed as 0.1? And the attack will display inexplicable fonts? And so is Sentinel Hammer

**Comment by AzureDoom** [comment]
The damage is applied via the tool system anymore but a damage check that's ran on use.

**Comment by wsxiya** [comment]
Strange fonts appear when attacking, is it because of OptiFine

**Comment by Tonahtiuh** [comment]
ive been looking everywhere for 1.19.2forge of this mod, where did you find the jar file? im trying to learn to modify the mods with eclipse i think? so that they run on a 1.19.2 server, i have no idea what im doing but im trying to learn. would i just replace any "1.19.3" to "1.19.2" in the code and somehow compile it to a jar file? i have an MDK but idk what its for lol gotta do more reading. ...also, i cannot just use 1.19.3 bc all the other mods arent on that version unless i learn to update them myself so either way i would need to learn how to update em. i know ur busy and this is most likely just a hobby for you but any help i would greatly appreciate

**Comment by AzureDoom** [comment]
I don't support optifine
